import Head from "next/head";
import Router from "next/router";
import * as Mui from "@mui/material";
import styles from "@/styles/Home.module.css";

const darkTheme = Mui.createTheme({
  palette: {
    mode: "dark",
  },
});

const Login = () => {
  return (
    <Mui.ThemeProvider theme={darkTheme}>
      <Mui.CssBaseline />
      <div className={styles.container}>
        <Head>
          <title>To-Do App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <form>
            <Mui.TextField
              label="Username"
              variant="outlined"
              id="outlined-basic"
              margin="normal"
              fullWidth
              required
            />
            <br />
            <Mui.TextField
              label="Password"
              type="password"
              variant="outlined"
              id="outlined-basic"
              margin="normal"
              fullWidth
              required
            />
            <br />
            <Mui.Button variant="contained">Login</Mui.Button>
          </form>
        </main>
      </div>
    </Mui.ThemeProvider>
  );
};

export default Login;
